### ISSUE TITLE
Differences to the R version

### ISSUE THREAD

**Issue by f6v** [amsszlh/scAI#3]
Thanks for sharing the package! I wanted to clarify two questions:
- Matlab version of scAI doesn't have a function to select k, does it?
- The Matlab version actually uses `chromVAR`, unlike the R package?

**Comment by f6v** [comment]
Just noticed https://github.com/amsszlh/scAI/blob/master/identify_consensus_cluster.m
I guess I could determine the cophenetic score with this function?
@amsszlh

**Comment by amsszlh** [comment]
Yes, K is selected base on the cophenetic score.
The chromVAR is used in Matlab version for downstream motif analysis.

**Comment by f6v** [comment]
Thanks!
