### ISSUE TITLE
Can't make run_scAI work

### ISSUE THREAD

**Issue by f6v** [amsszlh/scAI#4]
I'm following the A549 tutorial PDF, but with my own data.
Here's my code:

```
rna_counts = h5read(counts_path, "/RNA")
atac_counts = h5read(counts_path, "/ATAC")

c1 = median(rna_counts(rna_counts ~= 0));
c2 = median(atac_counts(atac_counts ~= 0));
atac_counts = atac_counts / c1 * c2

k = 2;
alpha = 1; lambda = 100000; gamma = 1; s = 0.25;
result = run_scAI(rna_counts, atac_counts, k, alpha, lambda, gamma, s);
result
```

I end up with the following error:
> Error using scAI
> Too many input arguments.
> Error in run_scAI (line 41)
>  [W1,W2,H,Z,R] = scAI(X1,X2,K,alpha,lambda,gamma,s,stop_rule,seeds(j));

`rna_counts` and `atac_counts` are both 2d matrices. 

Am I doing something wrong? 
Matlab versions are 2019b and 2018b.

**Comment by f6v** [comment]
I've also tried running the tutorial with the provided A549 data and get the same outcome.

**Comment by amsszlh** [comment]
Hi,
 What operating system you used? I tested it on Mac, it's OK.

**Comment by f6v** [comment]
@amsszlh thanks for getting back to me! I figured it out, it was my lack of experience with Matlab. I was compiling the code to run in my HPC environment as a binary, and named one of the files as `scAI`. As a result, there was a naming conflict that I didn't anticipate. Thanks for the support!
